function [edgeleft, edgeright, fitresult, gof] = diskfit_topimg(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Feb-2016 15:24:54


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'amp*real(sqrt(Rad^2-(x-x0)^2))+bg', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Robust = 'Bisquare';
opts.StartPoint = [45 0.03 0 70];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
edgeleft = fitresult.x0 - fitresult.Rad;
edgeright = fitresult.x0 + fitresult.Rad;

% % % Plot fit with data.
% % figure( 'Name', 'untitled fit 1' );
% % h = plot( fitresult, xData, yData );
% % legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% % % Label axes
% % xlabel x
% % ylabel y
% % grid on


